// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbwengugrepguvnuwfzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdid2VuZ3VncmVwZ3V2bnV3ZnpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MjEzODcsImV4cCI6MjA1OTE5NzM4N30.sEsOw4ORlrjlQNLyvRNgwtmp1S7iyXTTJsfoguj_q1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);